kurento-test: fix invalid HTML test pages, format
HTML was invalid because '</input>' is not a valid closing tag.
SyntaxError: Void elements do not have end tags "input" (77:15)

Also, format to make humanly readable, it was a mess! Use default
Prettier formatting options.